In [115]:
import pandas as pd 
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, classification_report, f1_score

In [116]:
iris_data=pd.read_csv("Iris.csv")

In [117]:
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [118]:
iris_data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [119]:
iris_data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [120]:
# convert 3 species into 0, 1, 2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
iris_data['Species'] = le.fit_transform(iris_data['Species'])

In [121]:
x= iris_data.drop(["Id","Species"], axis=1)
y= iris_data["Species"]

In [122]:
x.sample()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
18            5.7           3.8            1.7           0.3

In [123]:
y.sample()

120    2
Name: Species, dtype: int64

In [124]:
# Classification-Model --->  Logistic Regrssion

x_train,x_test,y_train,y_test= train_test_split(
    x, y, test_size=0.5, random_state=42
)

model1= LogisticRegression(max_iter=1000)

model1.fit(x_train,y_train)

y_predict= model1.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_predict)*100, "%")

print("Precision:",  precision_score(y_test, y_predict, average='macro')*100, "%")

print("Recall:", recall_score(y_test, y_predict, average='macro')*100, "%")

print("f1_score:", f1_score(y_test, y_predict, average='macro')*100 , "%")

print("Confusion-Matrix:", confusion_matrix(y_test,y_predict))
result = pd.DataFrame({
    "Actual": y_test,
    "Prediction": y_predict
})

print(result)

print("Classification-Report:", classification_report(y_test, y_predict)) # return string as output

Accuracy: 100.0 %
Precision: 100.0 %
Recall: 100.0 %
f1_score: 100.0 %
Confusion-Matrix: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
     Actual  Prediction
73        1           1
18        0           0
118       2           2
78        1           1
76        1           1
..      ...         ...
113       2           2
33        0           0
138       2           2
101       2           2
62        1           1

[75 rows x 2 columns]
Classification-Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

In [125]:
# Classification-Model --->  Naive_Bayes (Gaussian)

GNB_model= GaussianNB()

GNB_model.fit(x_train, y_train)

y_pred= GNB_model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred)*100, "%")

print("Precision:",  precision_score(y_test, y_pred, average='macro')*100, "%")

print("Recall:", recall_score(y_test, y_pred, average='macro')*100, "%")

print("f1_score:", f1_score(y_test, y_pred, average='macro')*100 , "%")

print("Confusion-Matrix:", confusion_matrix(y_test,y_pred))
result = pd.DataFrame({
    "Actual": y_test,
    "Prediction": y_pred
})

print(result)

print("Classification-Report:", classification_report(y_test, y_pred))

Accuracy: 98.66666666666667 %
Precision: 98.61111111111111 %
Recall: 98.55072463768116 %
f1_score: 98.55003940110323 %
Confusion-Matrix: [[29  0  0]
 [ 0 23  0]
 [ 0  1 22]]
     Actual  Prediction
73        1           1
18        0           0
118       2           2
78        1           1
76        1           1
..      ...         ...
113       2           2
33        0           0
138       2           2
101       2           2
62        1           1

[75 rows x 2 columns]
Classification-Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       0.96      1.00      0.98        23
           2       1.00      0.96      0.98        23

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

In [126]:
# Classification-Model --->  K-Nearest-Neghbour (KNN)

KNN_classifier= KNeighborsClassifier()

# use sklearn pipeline+gridsearch for make validation data unseen ()

from sklearn.pipeline import Pipeline
from  sklearn.model_selection import GridSearchCV

pipeline = Pipeline([
    ('scaler', StandardScaler()),  # only scale training data not validation data
    ('knn', KNeighborsClassifier())
])
K_val= {"knn__n_neighbors": [3,5,7,9]}
classifierCV= GridSearchCV(
    pipeline ,
    K_val ,    
    cv=5  ,   # folds
    scoring= "recall_macro"  # default accuracy
)

classifierCV.fit(x_train,y_train)
y_pred= classifierCV.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred)*100, "%")

print("Precision:",  precision_score(y_test, y_pred, average='macro')*100, "%")

print("Recall:", recall_score(y_test, y_pred, average='macro')*100, "%")

print("f1_score:", f1_score(y_test, y_pred, average='macro')*100 , "%")

print("Confusion-Matrix:", confusion_matrix(y_test,y_pred))
result = pd.DataFrame({
    "Actual": y_test,
    "Prediction": y_pred
})

print(result)

print("Classification-Report:", classification_report(y_test, y_pred))

Accuracy: 97.33333333333334 %
Precision: 97.33333333333333 %
Recall: 97.10144927536231 %
f1_score: 97.0959595959596 %
Confusion-Matrix: [[29  0  0]
 [ 0 23  0]
 [ 0  2 21]]
     Actual  Prediction
73        1           1
18        0           0
118       2           2
78        1           1
76        1           1
..      ...         ...
113       2           2
33        0           0
138       2           1
101       2           2
62        1           1

[75 rows x 2 columns]
Classification-Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       0.92      1.00      0.96        23
           2       1.00      0.91      0.95        23

    accuracy                           0.97        75
   macro avg       0.97      0.97      0.97        75
weighted avg       0.98      0.97      0.97        75